name: build-windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install flask flaskwebgui pyinstaller lxml beautifulsoup4
      - run: pyinstaller --onefile --windowed --hidden-import flaskwebgui --add-data "templates;templates" --add-data "static;static" app.py
        with:
          name: windows-exe
          path: dist/*.exe
